version: "3.8"
name: floq
services:
  floq-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_VOLUME_MOUNT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  floq-api:
    image: postgrest/postgrest:v11.2.2
    ports:
      - "3003:3000"
    environment:
      - PGRST_DB_SCHEMA=${PGRST_DB_SCHEMA}
      - PGRST_JWT_SECRET=${PGRST_JWT_SECRET}
      - PGRST_DB_URI=${PGRST_DB_URI}
    depends_on:
      - floq-db
