-- Revert floq:add_read_only_user from pg

BEGIN;

REVOKE ALL PRIVILEGES ON SCHEMA public FROM read_only;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM read_only;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM read_only;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM read_only;
REVOKE ALL PRIVILEGES ON DATABASE floq FROM read_only;
DROP USER IF EXISTS read_only;

COMMIT;
